### ISSUE TITLE
Input token pre-processing in `example.py`

### ISSUE THREAD

**Issue by matt-peters** [salesforce/cove#5]
Hello,

Thanks for releasing your code and nice paper!

I have a question about the token input pre-processing.  In the example:

https://github.com/salesforce/cove/blob/master/test/example.py#L8

the input tokens are lower cased.  However, the pre-trained GloVe 840B.300d vectors are case sensitive.  Is this intentional?  If I understand the code, this will have the effect of mapping "the" and "The" to the same vector in the CoVe implementation even though those tokens have different GloVe vectors.

**Comment by matt-peters** [comment]
Also, should the input text be tokenized?  The line in `example.py`:

https://github.com/salesforce/cove/blob/master/test/example.py#L8

does not pass a parameter for the `tokenize` keyword argument.  As a result, the tokenize is just a white space tokenizer: 

```python
from torchtext import data

inputs = data.Field(lower=True, include_lengths=True, batch_first=True)
print(inputs.tokenize("The family is outside."))
```

Displays:

```
['The', 'family', 'is', 'outside.']
```

**Comment by matt-peters** [comment]
Digging a little further, the `inputs` in `example.py` is inconsistent with respect to both lowercasing and the tokenizer with the assumed default in `datasets.SNLI.iters` in `torchtext`:

https://github.com/pytorch/text/blob/master/torchtext/datasets/snli.py#L108

**Comment by bmccann** [comment]
Yes, the example given is just showing how the MTLSTM might be used, but it is definitely not a recommendation of how to tokenize or otherwise handle the SNLI dataset. The MTLSTM was trained with Moses tokenization, so to match my experiments, you would need to both lowercase and use the Moses tokenizer on the SNLI dataset (or whichever dataset you are interested in using). This should be available in torchtext right now. This dumb demo example.py just didn't.
